# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
